import { MAP_HEIGHT, MAP_WIDTH, gridToWorld, worldToGrid } from "./gridUtils";
import { MAP_SEED, fbm2, hash2, noise2 } from "./mapGenerator";
import { createWorldPath, getPathPoint } from "./pathGenerator";
import { TileType, type DecorationDef, type MapConfig } from "./types";

const MAX_LARGE_VEGETATION = 1050;
const CARDINALS = [[1, 0], [-1, 0], [0, 1], [0, -1]] as const;
function distanceField(map: MapConfig, source: (x: number, z: number) => boolean) { const distances = Array.from({ length: MAP_HEIGHT }, () => Array(MAP_WIDTH).fill(Infinity)); const queue: { x: number; z: number }[] = []; for (let z = 0; z < MAP_HEIGHT; z++) for (let x = 0; x < MAP_WIDTH; x++) if (source(x, z)) { distances[z][x] = 0; queue.push({ x, z }); } for (let head = 0; head < queue.length; head++) { const current = queue[head]; for (const [dx, dz] of CARDINALS) { const x = current.x + dx; const z = current.z + dz; if (x < 0 || x >= MAP_WIDTH || z < 0 || z >= MAP_HEIGHT || distances[z][x] <= distances[current.z][current.x] + 1) continue; distances[z][x] = distances[current.z][current.x] + 1; queue.push({ x, z }); } } return distances; }
export function generateDecorations(map: MapConfig): DecorationDef[] {
  const decorations: DecorationDef[] = []; const roadDistance = distanceField(map, (x, z) => map.cells[z][x].type === TileType.Road); const edgeDistance = distanceField(map, (x, z) => map.cells[z][x].type === TileType.Sand); const { mainCurve, checkpoints } = createWorldPath(); const checkpointCells = checkpoints.map((checkpoint) => getPathPoint(mainCurve, checkpoint.t)).map((point) => worldToGrid(point.x, point.z)).filter((point): point is { x: number; z: number } => Boolean(point)); let largeVegetation = 0;
  for (let z = 0; z < map.height; z++) for (let x = 0; x < map.width; x++) { const cell = map.cells[z][x]; if (cell.type !== TileType.Grass) continue; const checkpointDistance = checkpointCells.reduce((best, point) => Math.min(best, Math.hypot(point.x - x, point.z - z)), Infinity); if (checkpointDistance < 2.7) continue; const world = gridToWorld(x, z); const h = hash2(x, z, MAP_SEED + 811); const roll = hash2(x, z, MAP_SEED + 977); const base = { x: world.x + (hash2(x, z, MAP_SEED + 1013) - 0.5) * 0.42, z: world.z + (hash2(x, z, MAP_SEED + 1091) - 0.5) * 0.42, rotation: h * Math.PI * 2, elevation: cell.elevation }; const cluster = fbm2(world.x * 0.115, world.z * 0.115, MAP_SEED + 313); const clearing = noise2(world.x * 0.055, world.z * 0.055, MAP_SEED + 457); const interior = Math.min(1, Math.max(0.18, edgeDistance[z][x] / 5)); const clearingFactor = clearing < 0.27 ? 0.13 : clearing < 0.34 ? 0.48 : 1; const jungleDensity = Math.min(0.92, (0.38 + cluster * 0.58) * interior * clearingFactor); const scale = 0.78 + hash2(x, z, MAP_SEED + 1217) * 0.48; const heightRoll = hash2(x, z, MAP_SEED + 1187); const heightCluster = fbm2(world.x * 0.065, world.z * 0.065, MAP_SEED + 1163); const heightSignal = heightCluster * 0.68 + heightRoll * 0.32; const heightScale = heightSignal < 0.38 ? 0.8 + heightRoll * 0.2 : heightSignal < 0.62 ? 1.02 + heightRoll * 0.24 : heightSignal < 0.78 ? 1.3 + heightRoll * 0.28 : 1.7 + heightRoll * 0.32; const canopyScale = 0.88 + hash2(x, z, MAP_SEED + 1201) * 0.27 + (heightScale > 1.55 ? 0.1 : 0); const largeClearance = heightScale > 1.42 ? 4 : 3; const checkpointClearance = heightScale > 1.42 ? 4.7 : 3.6;
    if (roadDistance[z][x] >= largeClearance && checkpointDistance >= checkpointClearance && largeVegetation < MAX_LARGE_VEGETATION && roll < (edgeDistance[z][x] <= 3 && edgeDistance[z][x] >= 1 ? 0.2 + jungleDensity * 0.18 : jungleDensity)) { const palm = edgeDistance[z][x] <= 3 && edgeDistance[z][x] >= 1 && hash2(x, z, MAP_SEED + 1301) < 0.58; const kind = palm ? "palm" : "tree"; decorations.push({ id: `${kind}-${x}-${z}`, ...base, kind, variant: Math.floor(hash2(x, z, MAP_SEED + 1399) * 6), scale, heightScale: kind === "palm" ? Math.max(1.05, heightScale * 0.88) : heightScale, canopyScale }); largeVegetation++; continue; }
    if (roadDistance[z][x] < 2) continue; const propRoll = hash2(x, z, MAP_SEED + 1487); if (propRoll < 0.11 + jungleDensity * 0.2) { const kindRoll = hash2(x, z, MAP_SEED + 1559); const kind: DecorationDef["kind"] = kindRoll < 0.62 ? "bush" : kindRoll < 0.78 ? "flower" : kindRoll < 0.93 ? "rock" : "log"; decorations.push({ id: `${kind}-${x}-${z}`, ...base, kind, variant: Math.floor(hash2(x, z, MAP_SEED + 1601) * 6), scale: 0.8 + hash2(x, z, MAP_SEED + 1693) * 0.35 }); }
  }
  return decorations;
}
